### PR TITLE
Today's updates

### PR DESCRIPTION
**Pull request by stephenbpurkiss**
Creating a pull request now as it's late and there's an interesting forum post I want to reply to.

A "major" change here is I'm getting confused by the custom field being called "content", I feel it's too much like a reserved name. I'm so confused I'm not even sure if my changes will affect the code, specifically:

      call: ({ create_entry }) => ({ greeting_text }) => {
        return create_entry({ greeting_text, entry_def_id: "greeting" });

which was:

      call: ({ create_entry }) => ({ content }) => {
        return create_entry({ content, entry_def_id: "greeting" });

I have got to a certain point in the text and will continue, I've changed all references to "content" to "greeting_text" and from "Hello World" to "Holo, World!", I thought it would be kinda cool / missed opportunity given the tone of your writing I thought it would fit in. On the subject of tone I've toned a few bits down to keep it concise - no need to say "well zomes don't do much but they do even when you're not looking" etc. - I found this a little confusing and distracting so hope the new text sounds ok and keeps your "character" but is just a little "tighter" ;)

I'll propose two changes on the developer-exercises repo with regards to the content->greeting_text and "Hello World" -> "Holo, World!", I'm sorry my memory fails me with git so I'm just doing it through the web UI at the moment, branching & stuff doing my head in. Flippin annoying having "learning difficulties", I can seemingly do some complicated things no problem but when it comes to relatively simple things my brain fails me hah!

Cheers,

sbp

### CODE REVIEW

**Comment by tixel** [comment]
Hi @stephenbpurkiss,
I get now what your pull requests in developer-exercises are about. Thanks for your explanation in this pull request.
I hope you are fine with me waiting a bit more before merging this in. I would like to add a few more basic exercises before improving on the existing one's. I received some feedback from Guillem, like moving some of the Rust tips to another place. I would like to incorporate that as well.

And thanks for spotting all my typing and spelling mistakes :bow:

**Comment by stephenbpurkiss** [comment]
Hah no problem, no rush, an apologies for my awful git fu, I'll catch up, it's just been a while!

Am enjoying the deep learning too, I was hacking assembler code 39 years ago, then BBC BASIC, then Pascal, then RPG/400 for IBM AS/400s in 1990 for a govt funded course and a year of "work experience" when I learned about relational databases - physical files stored the data, logical files stored the views, then ADA and Java at Uni, then J2EE, JSPs & Javabeans in the dotcom days c200, then a step back from OO to PHP, then into PHP to crazy abstraction in Drupal, then a mix of OO with Drupal rewrite from procedural to mostly OO, where I learned about traits and dependency injection, and now Rust.

You would think I'd be good at this by now lol but no, still confuses the hell out of me but I kinda enjoy it, and now I realise things like ADHD is why I have a small amount of knowledge about a wide range of things, and Autism means I dive deep into some things like user freedom-respecting software licensing lol!

I'm ranting, I'll leave you to it, thanks for all your work and giving something our future fellow humans have to control the machines with!

**Comment by stephenbpurkiss** [comment]
Just a quick update - I've added a markdown and git extension to visual studio so that's cool, am going to work on the changes I've made in this but not sure whether to "pull back" this pull request then create new one, will become clearer as I discover more, posting this so you know I've not just abandoned life the universe everything [inc. this] ;)

Have a great weekend!

**Comment by stephenbpurkiss** [comment]
...huh, nice to see VS has a `vim` emulator extension - was tempted but guess I should learn some new tricks ;)

**Comment by tixel** [comment]
Stephen, 

I pulled directly from your forked repository and merged into the master branch.
- Changing content to greeting_text was not possible since this breaks the simulation
- I kept "Hello world" instead of "Holo world" mainly because I hope it give a better change finding the gym when you search for "Holochain hello world example".

**Comment by stephenbpurkiss** [comment]
Hi @tixel

> Changing content to greeting_text was not possible since this breaks the simulation
How does it break the simulation?

> I kept "Hello world" instead of "Holo world" mainly because I hope it give a better change finding the gym when you search for "Holochain hello world example".
Good point, I hadn't thought of that! I did check and there are references to Holo World still and not all my other changes seem to be there so not sure if https://holochain-gym.github.io/developers/basic/entries/ is up-to-date or not.

**Comment by tixel** [comment]
Hi @stephenbpurkiss,

I do not know exactly why the simulation break if you do not use 'content'. Guillem has written all the playground simulations and I lake the knowledge, skills and free time to figure it out.

That aside, I do think you are right and that we should avoid using words like "content" where possible. Perhaps Guillem or somebody else will upgrade the playground simulation so that it will be possible.

**Comment by stephenbpurkiss** [comment]
Ok cool thanks - it is good to know that it broke, I presume it is only JavaScript so will have a play myself when my brain next lands on this ;)

**Comment by guillemcordoba** [comment]
Just pushed the change from content to greeting_text, you can see how to fix the simulation without breaking it :)

**Comment by stephenbpurkiss** [comment]
Awesome!

Only one sip into morning coffee but had a quick look... does "content" still need changing in the simulation perhaps?

Screenshot 2021-04-09 at 09 42 43

**Comment by stephenbpurkiss** [comment]
i.e. 
```
{
  "entry_type": "App",
  "greeting_text": "test"
}
```

**Comment by stephenbpurkiss** [comment]
OK, so think this is the point where I get the point - the "content" under the Entry Contents is indeed the content of greeting_text, and it is the key, so it is correct in being "content".

Blimey O'reilly I'm glad I'm extracting myself from the dirty details of this one, hopefully now it's less confusing for the next person - i.e. they shouldn't get confused because the field name is now greeting_text. 

Have a great weekend,

sup

**Comment by stephenbpurkiss** [comment]
(can't believe it took me inspecting the element on the web page and seeing it marked up as 'key' to finally get it lol)

**Pull request closed without merging**
